### ISSUE TITLE
Copying a slice to another slice in the same array fails silently

### ISSUE THREAD

**Issue by manopapad** [nv-legate/legate.numpy#16]
Bug report due to @piyueh

The following code, when run with `-lg:numpy:test`, prints `[False]`, indicating that the slice has not been updated:

```
from legate import numpy
a = numpy.random.random((3, 3))
a[:, 0] = a[:, 2]
print(numpy.allclose(a[:, 0], a[:, 2]))
```

After some digging I found that we skip copies between sub-regions if they're backed by the same field, which is actually only safe if the slices are equivalent: https://github.com/nv-legate/legate.numpy/blob/2b460c5dfdd60b673e37e25231bf625fdf3ead0e/legate/numpy/deferred.py#L101-L105

If we simply skip this check then the copy ends up happening through a CopyTask, which works with subregions of the same base region.

However, the runtime errors out if the two slices overlap, e.g. if we do `a[0,0:2] = a[0,1:3]` (vanilla NumPy accepts this, and does the expected thing). We should at least check for overlaps in python and produce a reasonable error message.

We also want to add a case for this to the test suite.

**Comment by lightsighter** [comment]
Here's another variation on this problem that we need to handle:

```
a[ [4,2,5,1,3] ] = b[2:7]
```

Requires an destination indirect (scatter) copy with an additional transform on the source.

**Comment by piyueh** [comment]
Hi, is it possible to raise a `NotImplementedError` when application code uses this kind of in-array copying? It seems it takes time to resolve it. However, this kind of copying is very common in numerical methods for solving PDEs, for example, in periodic boundary conditions and 1st-order approximation of Neumann boundary conditions. So I think raising an error to notify application developers is a better short-term solution.

Actually, even in the last step of the 12-step to CFD (the one used in GTC presentation), we also have this type of copying in `pressure_poisson_periodic`. (However, in this particular case, the pressure field does not change, so a failure in the copying does not affect the solution's correctness.)

Another example is the code shown in issue #29.

**Comment by manopapad** [comment]
Yes, I meant to tackle this properly after fixing #12, but that's taking longer than expected. I will add some error messages as a stopgap.

**Comment by manopapad** [comment]
As of b997647 the original testcase should be working. The case of overlapping sub-arrays is not working, but we will emit an error message about it. We also detect cases where a copy requires two indirections on a dimension, and error out.

**Comment by manopapad** [comment]
My last change uncovered that some of our tests are doing copies between overlapping sub-arrays, reverting until I can fix those.

**Comment by manopapad** [comment]
The original testcase should be properly working now with 5ec50990. @piyueh please let me know if it works for you. If it does I will update the issue to track work on relevant features that are still missing (handling overlapping regions in copies, handling views on advanced copies).

**Comment by piyueh** [comment]
Yes, I confirm the original test case is working now. Thanks!

**Comment by manopapad** [comment]
I have opened issues #39, #40 and #41 to track work on the remaining issues, closing this one.
