### ISSUE TITLE
Dockerfiles removed

### ISSUE THREAD

**Issue by asher-pembroke** [nv-legate/legate.numpy#2]
You have removed "outdated" dockerfiles. Are there plans to restore them?

**Comment by marcinz** [comment]
Going ahead, we plan to maintain Dockerfiles in the [quickstart repository](https://github.com/nv-legate/quickstart). I'll close this issue when the documentation is updated to say that.

**Comment by manopapad** [comment]
Documentation has been updated to point to the docker images
