### ISSUE TITLE
Documentation of the flag --no-openmp

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.numpy#3]
The documentation of `--no-openmp` says *"**Build Legate NumPy with OpenMP**"*. I'm kind of confused. Does `--no-openmp` disable or enable OpenMP? Thanks!

https://github.com/nv-legate/legate.numpy/blob/90601de0b1f03d0a1753776f3f37b1fe9d7f7972/install.py#L467-L474

**Comment by manopapad** [comment]
It seems there were some typos in our argument parsing code (and documentation), thanks for pointing this out! I have fixed it to work as expected (build with OpenMP by default, disable OpenMP with `--no-openmp`).
