### ISSUE TITLE
ImportError or NameError?

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.numpy#4]
In the example of Jacobi solver, the code uses `NameError` to catch import failure on `legate.numpy`. If the intention is to handle the situation when `legate.numpy` is not available/installed, is it better to catch `ImportFailure` instead? Thanks.

https://github.com/nv-legate/legate.numpy/blob/026061bd8b5d02ceb7fcb25be73cece6d302c767/examples/jacobi.py#L26-L29

**Comment by manopapad** [comment]
You are right! I changed the examples to use `ImportError` instead of `NameError`.
