### ISSUE TITLE
Need a way to pass build flag to OpenBLAS

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.numpy#5]
My CPU is Intel's Comet Lake, which can not be detected by OpenBLAS v0.3.10 automatically (see xianyi/OpenBLAS#2769). The solution suggested by OpenBLAS is either providing a flag `TARGET=...` or using later versions. However, `install.py` has hard-coded the OpenBLAS version to v0.3.10 and does not provide any methods to provide custom flags to build OpenBLAS.

Currently, I'm building my own OpenBLAS. I'm just thinking maybe it's nicer to have a way to provide custom OpenBLAS flags to `install.py`? Or at least add some notes in README to let users know they have to build/install their own OpenBLAS if they have newer CPUs?

Thanks!

**Comment by piyueh** [comment]
I'm closing this issue because now I feel it's not really an issue ...

**Comment by marcinz** [comment]
Just to comment, I bumped up the version of OpenBLAS to 0.3.13. This seems to be the latest stable version without any issues. We do have an option to provide your own OpenBLAS (`--with-openblas`), but as the option description states, providing your own OpenBLAS may lead to conflicts at library load time.
